name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v2

    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v1

    #   - name: Log in to Docker Registry
    #     run:  docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Build Docker image
    #     run: docker build -t registry.tungpham.bio/portfolio-fe:latest .

    #   - name: Push Docker image
    #     run: docker push registry.tungpham.bio/portfolio-fe:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: build

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 103.72.97.254
          username: root
          password: ichigo100
          port: 24700
          script: |
            docker pull ${{ secrets.DOCKER_HOST }}/portfolio-fe:latest
            docker stop portfolio-fe || true
            docker rm portfolio-fe || true
            docker run -d --name portfolio-fe -p 3000:3000 ${{ secrets.DOCKER_HOST }}/portfolio-fe:latest
